lattice-endpoint: <LATTICE_ENDPOINT>
lattice-client-id: <LATTICE_CLIENT_ID>
lattice-client-secret: <LATTICE_CLIENT_SECRET>
sandboxes-token: <SANDBOXES_TOKEN>

# Asset latitude and longitude
asset-latitude: 1
asset-longitude: 1

# Track latitude and longitude
track-latitude: 1.03
track-longitude: 1.03