lattice-endpoint: lattice-afard.env.sandboxes.developer.anduril.com
environment-token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NzEzODkwNDMsImlzcyI6ImFuZHVyaWwiLCJqdGkiOiI0ZDdmOWU3Ny1mZDYyLTQ1YzItYTkyNS04MjA3OGYzYzBhOTEiLCJuYmYiOjE3NzA3ODQyMzMsInN1YiI6InVzZXIvOWVkNDdiOWYtMTg4OC00MjkxLTg4YTMtY2UwOWIyYjc2ZDhjIiwidG9rZW5fc291cmNlIjoxfQ.raEQWtrNSlhzjJtI_8njvUSsNeK0YeJ2VIgESr1cGBk
sandboxes-token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NzcwNTk4MDUsImlzcyI6ImFuZHVyaWwiLCJqdGkiOiI3YTlhYzg3Yy00NjdjLTQ3MmQtODQ3YS0xOGM0OGRkMWQ0ZmQiLCJuYmYiOjE3NjkyODM3OTUsInN1YiI6InVzZXIvYjVhOTk2MmQtODk2OC00MTI1LWI5NzgtNTFjNmVjN2UyYjEyIiwidG9rZW5fc291cmNlIjoxfQ.g6ftU5XS5QvrQSnLFiKj9hdo615SBePGlOGgiU_wJeE

# Asset latitude and longitude
asset-latitude: 1
asset-longitude: 1

# Track latitude and longitude
track-latitude: 1.03
track-longitude: 1.03